### ISSUE TITLE
Dear author, I want to know how to train myself data

### ISSUE THREAD

**Issue by Yusin2Chen** [KAIST-VCLAB/deepcassi#1]
Dear author, In the coder, I can't some functions about how to train the autoencoder. Could you tell me how to train a new network? Thank you very much.

**Comment by inchangchoi** [comment]
Hi cyx66951!

We are glad that we could answer your question. 

In the code, the model definition of the autoencoder is included. Though we don't provide a code for training the network, you can train the model with some hyperspectral datasets.

Please refer to https://www.tensorflow.org/tutorials/layers for an example of training a network in tensroflow.

Thanks.
